### ISSUE TITLE
Error running program

### ISSUE THREAD

**Issue by Flaxoos** [discocube/weaver#2]
Got this at first attempt running:

```
 cargo run --release 1 100
    Finished release [optimized + debuginfo] target(s) in 0.17s
     Running `target/release/hamcycle 1 100`
| 🇳    1 | ⭕️          8 | 🕗 SOLVE: 0.0002328330 | 📌 HamCycle | 🕗 CERTIFY: 0.0000046250
| 🇳    2 | ⭕️         32 | 🕗 SOLVE: 0.0000054170 | 📌 HamCycle | 🕗 CERTIFY: 0.0000020840
| 🇳    3 | ⭕️         80 | 🕗 SOLVE: 0.0003580840 | 📌 HamCycle | 🕗 CERTIFY: 0.0000078750
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/graph/defs.rs:444:52
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:114:5
   3: core::option::Option<T>::unwrap
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/option.rs:823:21
   4: <std::collections::hash::set::HashSet<([i16; 3],[i16; 3])> as hamcycle::graph::defs::Bridge<std::collections::hash::set::HashSet<([i16; 3],[i16; 3])>>>::bridge
             at ./src/graph/defs.rs:444:52
   5: hamcycle::graph::weave::weave::{{closure}}
             at ./src/graph/weave.rs:88:27
   6: <core::slice::iter::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/slice/iter/macros.rs:201:21
   7: hamcycle::graph::weave::weave
             at ./src/graph/weave.rs:86:5
   8: hamcycle::find_solutions
             at ./src/main.rs:78:20
   9: hamcycle::main
             at ./src/main.rs:66:9
  10: core::ops::function::FnOnce::call_once
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5

```

**Comment by discocube** [comment]
Thanks for the issue, it's been corrected and a github workflow added to ensure it at least compiles all the time.
